// Generated by CoffeeScript 1.6.3
(function() {
  var Info, dir, expect, info, path;

  expect = require('chai').expect;

  path = require('path');

  Info = require('../../lib/Info');

  dir = path.normalize(__dirname + '/../data/test/node_modules');

  info = null;

  describe('Info.self', function() {
    return describe('#getMainFile()', function() {
      return it('should get main file for advanced module', function() {
        var main;
        info = Info.self(module);
        main = info.getMainFile();
        return expect(main).to.be.equal(path.normalize(__dirname + '/../../lib/Info.js'));
      });
    });
  });

}).call(this);
